# Generated by Django 5.1.6 on 2025-04-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandSign',
        ),
    ]
