# Generated by Django 5.1.6 on 2025-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TalentHive', '0006_delete_candsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5-8 years)'), ('expert', 'Expert Level (8+ years)'), ('manager', 'Manager Level'), ('executive', 'Executive Level')], max_length=20)),
                ('workplace_type', models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('usd', 'USD - US Dollar'), ('eur', 'EUR - Euro'), ('gbp', 'GBP - British Pound'), ('cad', 'CAD - Canadian Dollar')], max_length=3)),
                ('salary_frequency', models.CharField(max_length=20)),
                ('hide_salary', models.BooleanField(default=False)),
                ('company_overview', models.TextField()),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('required_skills', models.JSONField()),
                ('preferred_skills', models.JSONField()),
                ('education_level', models.CharField(max_length=100)),
                ('languages', models.JSONField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('receiving_applications', models.CharField(max_length=50)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('application_questions', models.JSONField()),
                ('required_documents', models.JSONField()),
                ('visibility', models.CharField(max_length=20)),
                ('featured_job', models.BooleanField(default=False)),
                ('urgent_job', models.BooleanField(default=False)),
                ('publish_option', models.CharField(max_length=20)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
