# Generated by Django 5.1.6 on 2025-04-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
