# Generated by Django 5.1.6 on 2025-04-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0010_customuser_hrprofile_candidateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='HRProfile',
        ),
    ]
