# Generated by Django 5.1.6 on 2025-05-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0017_candidateprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
    ]
