# Generated by Django 5.1.6 on 2025-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0021_candidate_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('hr', 'HR'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
