# Generated by Django 5.1.6 on 2025-05-03 10:10

import TalentHive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0022_candidate_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='newsletter_subscribed',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='terms_accepted',
        ),
        migrations.AddField(
            model_name='hr',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=TalentHive.models.Company.company_logo_path),
        ),
        migrations.AlterField(
            model_name='hr',
            name='company_size',
            field=models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hr',
            name='industry',
            field=models.CharField(choices=[('it', 'Information Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('other', 'Other')], max_length=100),
        ),
    ]
