# Generated by Django 5.1.6 on 2025-05-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0023_remove_hr_newsletter_subscribed_remove_hr_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
