# Generated by Django 5.1.6 on 2025-05-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0024_hr_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='status',
        ),
    ]
