# Generated by Django 5.1.6 on 2025-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0028_user_reset_password_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hr_users',
            field=models.ManyToManyField(limit_choices_to={'role': 'hr'}, related_name='companies', to='TalentHive.user'),
        ),
    ]
