# Generated by Django 5.1.6 on 2025-04-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TalentHive', '0008_delete_jobposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=50)),
                ('workplace_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hide_salary', models.BooleanField(default=False)),
                ('company_overview', models.TextField()),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('required_skills', models.TextField()),
                ('preferred_skills', models.TextField()),
                ('education_level', models.CharField(choices=[('high_school', 'High School Diploma/GED'), ('associate', "Associate's Degree"), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate/PhD'), ('professional', 'Professional Degree (MD, JD, etc.)'), ('certification', 'Professional Certification'), ('none', 'No Specific Requirement')], max_length=50)),
                ('languages', models.TextField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('require_resume', models.BooleanField(default=True)),
                ('require_cover_letter', models.BooleanField(default=False)),
                ('require_portfolio', models.BooleanField(default=False)),
                ('require_references', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Only visible with direct link'), ('company', 'Company - Only visible to your company employees')], max_length=50)),
                ('featured_job', models.BooleanField(default=False)),
                ('urgent_job', models.BooleanField(default=False)),
                ('publish_option', models.CharField(choices=[('publish_now', 'Publish immediately'), ('save_draft', 'Save as draft'), ('schedule', 'Schedule publishing')], max_length=50)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
