# Generated by Django 5.1.6 on 2025-04-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0012_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='confirm_password',
        ),
    ]
