# Generated by Django 5.1.6 on 2025-04-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0013_remove_candidate_confirm_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
