# Generated by Django 5.1.6 on 2025-05-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0020_delete_candidateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
