# Generated by Django 5.1.6 on 2025-05-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0025_remove_hr_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='User',
        ),
    ]
