# Generated by Django 5.1.6 on 2025-05-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0030_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
