# Generated by Django 5.1.6 on 2025-05-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentHive', '0031_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='TalentHive.company'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='hr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='TalentHive.user'),
        ),
    ]
